### ISSUE TITLE
Fix the status bar color

### ISSUE THREAD

**Issue by shankarlohar** [DSCVITBHOPAL/Coffee-Shopping-App#5]
![WhatsApp Image 2022-03-04 at 9 23 28 PM (2)](https://user-images.githubusercontent.com/74100292/156813583-ff1a88b1-9bbc-43a4-999e-97b5ccf702f2.jpeg)

Make it match to the app theme...

**Comment by udit6023** [comment]
Here are some ss for the same
![Screenshot1](https://user-images.githubusercontent.com/91983775/156935357-8fde659e-0b11-4fa3-9cc2-ef931b3b1e1f.png)
![Screenshot2](https://user-images.githubusercontent.com/91983775/156935367-b17b4be7-1912-4b1c-868a-cb3f5e2543bb.png)
![Screenshot3](https://user-images.githubusercontent.com/91983775/156935371-08f2d9db-4725-4e13-b127
![Screenshot3](https://user-images.githubusercontent.com/91983775/156935372-ed2cd55a-fc9c-41ae-823d-6d4bfc9356fb.png)
![Screenshot2](https://user-images.githubusercontent.com/91983775/156935373-ac1c11d0-af2d-4e79-a1a2-80d96a4b9709.png)
-1ad305329f27.png)

**Comment by ShankarLohar** [comment]
Hey! That's really really amazing. Great work!
> You can create a pull request with your code changes. 😎
> Make sure you update the screenshots in the Readme.md 😊
Good Job.

**Comment by udit6023** [comment]
Glad you liked it.
ya i am on it  :)

**Comment by shreyxnsh** [comment]
Is the issue still open?

**Comment by shankarlohar** [comment]
> Is the issue still open?

Yes Go For It!


PS:  I suggest using and learning compose.
